---
# Example Playbook: VLAN configuration using the [ucs] hosts group
- hosts: ucs
  connection: local
  gather_facts: no
  tasks:
  - name: Configure VLAN
    ucs_vlans:
      hostname: "{{ inventory_hostname }}"
      username: "{{ username | default(omit) }}"
      password: "{{ password }}"
      state: "{{ state | default(omit) }}"
      name: vlan2
      id: '2'
      native: 'no'
