---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - common

- hosts: ucsdevi
  connection: local
  gather_facts: no
  tasks:
  - name: remove boot order
    cisco_ucs_boot_policy:
      name: KUBAM
      ucs_ip: "{{ucs_ip}}"
      ucs_username: "{{ucs_username}}"
      ucs_password: "{{ucs_password}}"
      state: absent

  - name: remove lan connectivity policy
    cisco_ucs_lan_connectivity:
      lan_conn_list: "{{ lan_conn_list }}"
      ucs_ip: "{{ucs_ip}}"
      ucs_username: "{{ucs_username}}"
      ucs_password: "{{ucs_password}}"
      state: absent
  - name: remove vNIC templates
    cisco_ucs_vnic_template:
      vnic_list: "{{ vnic_list }}"
      ucs_ip: "{{ucs_ip}}"
      ucs_username: "{{ucs_username}}"
      ucs_password: "{{ucs_password}}"
      state: absent
  - name: remove Mac Pools
    cisco_ucs_macpool:
      mac_list: "{{ mac_list }}"
      ucs_ip: "{{ucs_ip}}"
      ucs_username: "{{ucs_username}}"
      ucs_password: "{{ucs_password}}"
      state: absent
  
  
  
