---

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
  - common

- hosts: ucsdevi
  connection: local
  gather_facts: no
  roles:
  - network
  - storage
  - server
  tasks:
  - name: KUBAM Service Profile
    cisco_ucs_spt:
      spt_list: "{{ service_profile_template }}"
      ucs_ip: "{{ ucs_ip}}"
      ucs_username: "{{ ucs_username }}"
      ucs_password: "{{ ucs_password }}" 


