---
- name: Ensure server pool is created
  cisco_ucs_server_pool: 
    pool: "{{ server_pool_list }}"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"
    

- name: Ensure bios policy is created
  cisco_ucs_bios_policy:
    name: "{{ bios_policy_name }}"
    descr: "Make sure the BIOS policy allows for cdn control."
    cdn_control: "enabled"
    resume_on_power_loss: "last-state"
    reboot_on_update: "yes"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

- name: Ensure scrub policy is created
  cisco_ucs_scrub_policy:
    name: "{{ scrub_policy_name }}"
    descr: "Destroy disks when disassociated."
    disk_scrub: "yes"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

- name: Ensure virtual media policy is created.
  cisco_ucs_vmedia_policy:
    name: "{{ vmedia_policy_name }}"
    descr: OS Boot VMedia
    retry: "yes"
    mounts:
    - name: esxi6.0
      descr: VMware Install Media
      device: cdd
      protocol: http
      remote_ip: 172.28.225.135
      file: variable
      path: kubam
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

- name: Ensure boot policy is created
  cisco_ucs_boot_policy: 
    name: "{{ boot_policy_name }}"
    reboot_on_update: "yes"
    enforce_vnic_name: "yes"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"
    
- name: Ensure boot order policy is created
  cisco_ucs_boot_order:
    name: "{{ boot_order_name }}"
    devices: "{{ boot_devices }}"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

- name: ensure UUID pool is created
  cisco_ucs_uuid:
    uuid_pool: "{{ uuid_pool }}"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

