---
- name: ensure KUBAM bios policy is created
  cisco_ucs_bios_policy:
    name: "KUBAM"
    descr: "Make sure the BIOS policy allows for cdn control."
    cdn_control: "enabled"
    resume_on_power_loss: "last-state"
    reboot_on_update: "yes"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

- name: ensure KUBAM scrub policy is created
  cisco_ucs_scrub_policy:
    name: "KUBAM"
    descr: "Destroy disks when disassociated."
    disk_scrub: "yes"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

- name: Ensure virtual media policy is created.
  cisco_ucs_vmedia_policy:
    name: KUBAM
    descr: OS Boot VMedia
    retry: "yes"
    mounts:
    - name: esxi6.0
      descr: VMware Install Media
      device: cdd
      protocol: http
      remote_ip: 172.28.225.135
      file: variable
      path: kubam
    - name: redhat7.3
      descr: CentOS image
      device: hdd
      protocol: http
      remote_ip: 172.28.225.135
      file: "centos.img"
      path: kubam
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

- name: ensure KUBAM boot policy
  cisco_ucs_boot_policy: 
    name: KUBAM
    reboot_on_update: "yes"
    enforce_vnic_name: "yes"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"
    
- name: ensure KUBAM boot order
  cisco_ucs_boot_order:
    name: KUBAM
    devices: "{{ boot_devices }}"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

- name: ensure KUBAM UUID pool is created
  cisco_ucs_uuid:
    uuid_pool: "{{ uuid_pool }}"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"

