---
# This role contains tasks for configuring storage settings

- name: Ensure disk group policy
  cisco_ucs_disk_group_policy:
    disk_group_policy_list: "{{ disk_group_policy_list }}"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"
    

- name: Ensure storage profile exists
  cisco_ucs_storage_profile:
    storage_profile: "{{ storage_profile }}"
    ucs_ip: "{{ucs_ip}}"
    ucs_username: "{{ucs_username}}"
    ucs_password: "{{ucs_password}}"
